CREATE DATABASE IF NOT EXISTS CH04_SPRINGDATAJPA;
CREATE DATABASE IF NOT EXISTS CH05_GENERATOR;
CREATE DATABASE IF NOT EXISTS CH05_MAPPING;
CREATE DATABASE IF NOT EXISTS CH05_SUBSELECT;
CREATE DATABASE IF NOT EXISTS CH06_MAPPING_VALUE_TYPES;

