CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INTEGER,
    unit_price NUMERIC(38, 2) NOT NULL,
    total_price NUMERIC(38, 2)
);
