spring.application.name=gateway
spring.cloud.gateway.server.webflux.routes[0].id=product-route
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=PrefixPath=/api
# Filter 1: AddResponseHeader (dùng cú pháp fully expanded)
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=AddResponseHeader
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.name=X-Powered-By
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.value=Phuong Gateway Service

spring.cloud.gateway.server.webflux.routes[1].id=order-route
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=PrefixPath=/api
spring.cloud.gateway.server.webflux.routes[1].filters[1].name=AddResponseHeader
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.name=X-Powered-By
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.value=Phuong Gateway Service
